## WINDOWS 32 BIT DESKTOP APPLICATION

This is my simple start desktop application 
using win32 API. Generated by Dev Cpp. 
The program will loaded a red ball and then bouncing 
around whenever the ball is hit the border of the window.